# Generated by Django 5.2.4 on 2025-07-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesticideschedule',
            old_name='application_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='pesticideschedule',
            old_name='pesticide_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='pesticideschedule',
            name='next_application_date',
        ),
        migrations.AddField(
            model_name='pesticideschedule',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
